services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      platforms:
        - linux/amd64
    image: ghcr.io/stealkiller06/portfolio:latest
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
      - HOSTNAME=0.0.0.0
      - NEXT_TELEMETRY_DISABLED=1
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:3000"]
      interval: 10s
      timeout: 5s
      retries: 3
